// <auto-generated />
using System;
using ChupinVetAgenda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChupinVetAgenda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ChupinVetAgenda.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailResponsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EspeciePet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HorarioDisponivelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomePet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HorarioDisponivelId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ChupinVetAgenda.Models.HorarioDisponivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HorariosDisponiveis");
                });

            modelBuilder.Entity("ChupinVetAgenda.Models.Agendamento", b =>
                {
                    b.HasOne("ChupinVetAgenda.Models.HorarioDisponivel", "HorarioDisponivel")
                        .WithMany()
                        .HasForeignKey("HorarioDisponivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioDisponivel");
                });
#pragma warning restore 612, 618
        }
    }
}
